import { Achievement } from "../types";


const achievementsData: Achievement[] = [
    {
        id: 1,
        category: 'Task Setting',
        name: 'Task Starter',
        description: 'Create your first task in TaskJourney.',
        progress: 100,
        completed: true,
        dateCompleted: new Date(),
    },
    {
        id: 2,
        category: 'Task Setting',
        name: 'Daily Task Achiever',
        description: 'Complete your daily tasks for 7 consecutive days.',
        progress: 0,  // Start with 0 progress
        completed: false,
        dateCompleted: null,
    },
    {
        id: 4,
        category: 'Task Completion',
        name: 'Consecutive Days',
        description: 'Complete tasks for 5 consecutive days.',
        progress: 0,
        completed: false,
        dateCompleted: null,
    },

    {
        id: 6,
        category: 'Task Completion',
        name: 'Milestone Achiever',
        description: 'Reach a milestone goal (e.g., complete 50 tasks).',
        progress: 0,
        completed: false,
        dateCompleted: null,
    },
    {
        id: 8,
        category: 'Task Completion',
        name: 'Task Master',
        description: 'Complete 100 tasks in TaskJourney.',
        progress: 0,
        completed: false,
        dateCompleted: null,
    },
    {
        id: 10,
        category: 'Calendar',
        name: 'Planner',
        description: 'Plan tasks for a week using the calendar feature.',
        progress: 0,
        completed: false,
        dateCompleted: null,
    },
    {
        id: 11,
        category: 'Calendar',
        name: 'Monthly Planner',
        description: 'Plan tasks for an entire month using the calendar.',
        progress: 0,
        completed: false,
        dateCompleted: null,
    },
    {
        id: 12,
        category: 'Calendar',
        name: 'Event Creator',
        description: 'Create and manage 5 events on the calendar.',
        progress: 0,
        completed: false,
        dateCompleted: null,
    },
    {
        id: 13,
        category: 'Special',
        name: 'Secret Explorer',
        description: 'Find and unlock a hidden feature in TaskJourney.',
        progress: 0,
        completed: false,
        dateCompleted: null,
    },
    {
        id: 14,
        category: 'Special',
        name: 'Easter Egg Hunter',
        description: 'Discover and complete all Easter eggs in TaskJourney.',
        progress: 0,
        completed: false,
        dateCompleted: null,
    },
    {
        id: 15,
        category: 'Community',
        name: 'Feature Advocate',
        description: 'Suggest a new feature or improvement and have it implemented.',
        progress: 0,
        completed: false,
        dateCompleted: null,
    },
    {
        id: 16,
        category: 'Community',
        name: 'Feedback Contributor',
        description: 'Provide feedback or suggestions for TaskJourney.',
        progress: 0,
        completed: false,
        dateCompleted: null,
    },
    {
        id: 17,
        category: 'Community',
        name: 'Early Adopter',
        description: 'Be one of the first 100 users to join TaskJourney.',
        progress: 0,
        completed: false,
        dateCompleted: null,
    },
    {
        id: 18,
        category: 'Community',
        name: 'Referral Champion',
        description: 'Refer 5 friends to TaskJourney and have them join.',
        progress: 0,
        completed: false,
        dateCompleted: null,
    },
    {
        id: 19,
        category: 'Growth',
        name: 'Goal Setter',
        description: 'Set 10 new goals in TaskJourney.',
        progress: 0,
        completed: false,
        dateCompleted: null,
    },
    {
        id: 20,
        category: 'Task Completion',
        name: 'Task Completer',
        description: 'Complete 250 tasks.',
        progress: 0,
        completed: false,
        dateCompleted: null,
    },
    {
        id: 21,
        category: 'Task Completion',
        name: 'Streak Setter',
        description: 'Achieve a 30-day task completion streak.',
        progress: 0,
        completed: false,
        dateCompleted: null,
    },
    {
        id: 22,
        category: 'Community',
        name: 'Community Builder',
        description: 'Engage with the community by commenting or liking posts.',
        progress: 0,
        completed: false,
        dateCompleted: null,
    },
    {
        id: 23,
        category: 'Special',
        name: 'Hidden Gem',
        description: 'Unlock a secret badge or achievement.',
        progress: 0,
        completed: false,
        dateCompleted: null,
    },
    {
        id: 24,
        category: 'Special',
        name: 'Mystery Solver',
        description: 'Complete a secret task or puzzle within TaskJourney.',
        progress: 0,
        completed: false,
        dateCompleted: null,
    },
    {
        id: 25,
        category: 'Special',
        name: 'Unseen Achiever',
        description: 'Achieve an achievement that is hidden or not visible initially.',
        progress: 0,
        completed: false,
        dateCompleted: null,
    },
    {
        id: 26,
        category: 'Streak',
        name: 'Streak Setter I',
        description: 'Achieve a 7-day streak.',
        progress: 0,
        completed: false,
        dateCompleted: null,
    },
    {
        id: 27,
        category: 'Streak',
        name: 'Streak Setter II',
        description: 'Achieve a 14-day streak.',
        progress: 0,
        completed: false,
        dateCompleted: null,
    },
    {
        id: 28,
        category: 'Streak',
        name: 'Streak Setter III',
        description: 'Achieve a 30-day streak.',
        progress: 0,
        completed: false,
        dateCompleted: null,
    },
    {
        id: 29,
        category: 'Streak',
        name: 'Streak Setter IV',
        description: 'Achieve a 90-day streak.',
        progress: 0,
        completed: false,
        dateCompleted: null,
    },
    {
        id: 30,
        category: 'Streak',
        name: 'Streak Setter V',
        description: 'Achieve a 1-year streak.',
        progress: 0,
        completed: false,
        dateCompleted: null,
    }
];


export default achievementsData;
